### PR TITLE
Add license CC-BY-SA 4.0

### PR DESCRIPTION
**Pull request by robredpath**
Thanks for your reply on #14 , @eandre . I've suggested the CC BY-SA license here, as I think it puts into (more) words what you're describing as to how you're happy for this to be used.

### CODE REVIEW

**Comment by robredpath** [comment]
(The SA means that anyone who builds on it also has to share that work back. If you don't care about that, then let me know and I'll happily shift it to just being the BY license, which means that attribution is required)

**Comment by timmwille** [comment]
thx, this is perfect

**Comment by evildmp** [comment]
Thanks @robredpath. I have had a chance to look at the licences more closely. I would like to use "CC BY-NC-SA 4.0" (i.e. with the non-commercial clause as well. Were you able to download this from somewhere? Or did you have to mark it all up by hand?

**Comment by robredpath** [comment]
Thanks @evildmp - I used the Markdown versions of the CC license from https://github.com/idleberg/Creative-Commons-Markdown/tree/master/4.0 - it's an unofficial repo, but reliable in my experience. 

For my purposes, it would be a shame to see this licensed under NC - my work is helping various organisations (principally charities, governments, activists and journalists) produce and use open data, but because we get paid for it, we couldn't use your work. Obviously, we can still refer to it (as we already do!), but I was hoping to be able to reproduce extracts - in particular diagrams - in our reports and materials, so that we don't need to send people off to another website in order to understand what we're saying. 

That said - it's obviously your call, and I'll respect whatever decision you come to - this is where having a license really helps everyone be clear on the author's wishes :)

**Comment by timmwille** [comment]
NC is only for private personal use, heavily discussed in the open source community and definitely not fitting with the Open Source definition. So in case collaboration is a goal, NC is not helpful and rather trouble as people misunderstand it as 'non profit' but it is not it is just forbidding anyone to use this in organisational context e.g. if the trainer or teacher is getting a fee. 

So I agree fully with @robredpath it is your call. Only I can't use it at the university as example for Open Source Hardware documentation then or would have to rebuild from ground up my own version, I also have suggestions/adoptions in place I would like to share.

**Comment by evildmp** [comment]
@timmwille @robredpath Thanks for the clarification. Preventing it being adopted/adapted in e.g. a university context is definitely not what I would like.

So in that case, I think CC-BY-SA 4.0 should be OK.

**Pull request merged**
